export interface BotBlock {
  provider: string;
  detail: string;
}

interface Signature {
  provider: string;
  /** Any header condition matching counts. */
  header?: (h: Headers) => boolean;
  /** Header is an explicit challenge signal, valid on any status (else only on 403/406/429/503). */
  definitive?: boolean;
  /** Any body marker (case-insensitive) matching counts. */
  markers?: string[];
}

const SIGNATURES: Signature[] = [
  {
    provider: "Cloudflare",
    header: (h) => h.get("cf-mitigated") === "challenge",
    definitive: true,
    markers: [
      "just a moment...",
      "cf-chl-",
      "_cf_chl_opt",
      "challenge-platform",
      "cf-browser-verification",
      "attention required! | cloudflare",
      "sorry, you have been blocked",
      "cf-error-details",
    ],
  },
  { provider: "Sucuri", markers: ["sucuri website firewall", "access denied - sucuri", "sucuri cloudproxy"] },
  { provider: "Imperva / Incapsula", markers: ["_incapsula_resource", "incapsula incident id", "request unsuccessful. incapsula"] },
  { provider: "Akamai", header: (h) => /akamaighost/i.test(h.get("server") ?? ""), markers: ["reference&#32;&#35;"] },
  { provider: "DDoS-Guard", header: (h) => /ddos-guard/i.test(h.get("server") ?? ""), markers: ["ddos-guard"] },
  { provider: "Wordfence", markers: ["generated by wordfence", "wordfence-blocked", "your access to this site has been limited"] },
  { provider: "ModSecurity", markers: ["mod_security", "modsecurity", "not acceptable!</h1>"] },
  { provider: "Vercel", header: (h) => h.get("x-vercel-mitigated") === "challenge", definitive: true },
  { provider: "hosting firewall", markers: ["bot verification", "verify you are human", "checking your browser before accessing"] },
];

/** Statuses a WAF / bot shield typically answers with. */
const BLOCK_STATUSES = new Set([403, 406, 429, 503]);

/**
 * Detect a bot-protection / WAF response instead of the real page.
 * Such responses are reported as BLOCKED (WARN), never as DOWN: the site is
 * very likely up for humans, it just doesn't like our monitor.
 */
export function detectBotProtection(status: number, headers: Headers, body: string): BotBlock | null {
  // Explicit challenge headers count on any status; server-type headers only on block statuses
  // (a DDoS-Guard/Akamai-fronted site also sends them on normal 200 responses).
  for (const sig of SIGNATURES) {
    if (sig.header?.(headers) && (sig.definitive || BLOCK_STATUSES.has(status))) {
      return { provider: sig.provider, detail: `${sig.provider} challenge (HTTP ${status})` };
    }
  }
  if (!BLOCK_STATUSES.has(status)) return null;

  const snippet = body.slice(0, 64 * 1024).toLowerCase();
  for (const sig of SIGNATURES) {
    if (sig.markers?.some((m) => snippet.includes(m))) {
      return { provider: sig.provider, detail: `${sig.provider} blocked the request (HTTP ${status})` };
    }
  }
  if (status === 429) return { provider: "rate limiter", detail: "Rate limited (HTTP 429 Too Many Requests)" };
  // Cloudflare-served 403 without a recognizable page is still almost always a WAF rule.
  if (status === 403 && (headers.get("server") ?? "").toLowerCase() === "cloudflare") {
    return { provider: "Cloudflare", detail: "Cloudflare WAF rule (HTTP 403)" };
  }
  return null;
}
